#端口 访问路径
server:
  port: 8081
  servlet:
    context-path: /

#spring配置
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///offcnpe
    username: root
    password: root

#mybatis-plus
mybatis-plus:
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true
    #控制台显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #加载xml文件
  mapper-locations: classpath:/mappers/*.xml
  #设置别名
  type-aliases-package: com.psi.pojo

#Dubbo端口，名称
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.128.128:2181
    timeout: 10000
  scan:
    base-packages: com.psi.provider.service.impl