server:
  servlet:
    context-path: /
  port: 8081

spring:
  application:
    name: offcnpe_controller
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///offcnpe
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: 192.168.128.128
    port: 6379
    password: root
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.128.128:2181
    timeout: 20000