server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: offcnpe_controller
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///offcnpe
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: 192.168.128.128
    port: 6379
    password: root
  servlet:
    multipart:
      #单个文件上传大小限制
      max-file-size: 10MB
      #单个请求文件总大小：不限
      max-request-size: -1


dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.128.128:2181
    timeout: 60000